#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/Users/knuterikborgen/kode/gwt-2.0.3/gwt-user.jar:/Users/knuterikborgen/kode/gwt-2.0.3/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src no.knubo.accounting.admin.client.Elements  ;

