<?php
/**
 * WikkaWiki configuration file 
 * 
 * This file was generated by the Wikka installer on Mon Apr 12 21:26:02 2010
 * Do not manually change wakka_version if you wish to keep your engine up-to-date.
 * Documentation is available at: http://docs.wikkawiki.org/ConfigurationOptions
 */
$wakkaConfig = array(
	'mysql_host' => 'localhost',
	'mysql_database' => 'bsc_kopi',
	'mysql_user' => 'root',
	'table_prefix' => 'wikka2_',
	'root_page' => 'Startside',
	'wakka_name' => 'Fritt Regnskap',
	'base_url' => 'http://localhost/wakka/wikka.php?wakka=',
	'rewrite_mode' => '0',
	'wiki_suffix' => '@wikka',
	'enable_user_host_lookup' => '1',
	'action_path' => 'plugins/actions,actions',
	'handler_path' => 'plugins/handlers,handlers',
	'gui_editor' => '1',
	'theme' => 'indigo',
	'wikka_formatter_path' => 'plugins/formatters,formatters',
	'wikka_highlighters_path' => 'formatters',
	'geshi_path' => '3rdparty/plugins/geshi',
	'geshi_languages_path' => '3rdparty/plugins/geshi/geshi',
	'wikka_template_path' => 'plugins/templates,templates',
	'safehtml_path' => '3rdparty/core/safehtml',
	'referrers_purge_time' => '30',
	'pages_purge_time' => '0',
	'xml_recent_changes' => '10',
	'hide_comments' => '0',
	'require_edit_note' => '0',
	'anony_delete_own_comments' => '1',
	'public_sysinfo' => '0',
	'double_doublequote_html' => 'safe',
	'sql_debugging' => '0',
	'admin_users' => 'KnutErikBorgen',
	'admin_email' => 'knutbo@ifi.uio.no',
	'upload_path' => 'uploads',
	'mime_types' => 'mime_types.txt',
	'geshi_header' => 'div',
	'geshi_line_numbers' => '1',
	'geshi_tab_width' => '4',
	'grabcode_button' => '1',
	'wikiping_server' => '',
	'default_write_acl' => '+',
	'default_read_acl' => '*',
	'default_comment_acl' => '*',
	'allow_user_registration' => '1',
	'enable_version_check' => '1',
	'version_check_interval' => '1h',
	'wakka_version' => '1.2',
	'mysql_password' => '',
	'meta_keywords' => '',
	'meta_description' => '',
	'stylesheet_hash' => '15456');
?>